#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Gyro,     sensorI2CCustom)
#pragma config(Sensor, S3,     light,           sensorI2CCustom9V)
#pragma config(Sensor, S4,     HTPB,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          RamRight,      tmotorNXT, openLoop)
#pragma config(Motor,  motorB,         RamLeft,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     RightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     LeftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     LeftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lifter,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     lifter,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    BamContR,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    BamContL,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Utilities/RobotMoveUtilities.c"
#include "../Configuration/RobotConfig.c"

//////////////////////////////////////////////////////////////////////////
void selectProgram()
{
	eraseDisplay();
	// Enable Top Line NXT Display (Bluetooth, NXT Name & Battery Status)
	bNxtLCDStatusDisplay = true;
	// StopAllTasks();
	while(true)
	{
		nxtDisplayCenteredTextLine(1,"DITU SAYS WEAR");
		nxtDisplayCenteredTextLine(2,"SAFETY GLASSES");
		nxtDisplayCenteredTextLine(4, "Select Test:");
		//------------------------------------------------
		if(nNxtButtonPressed == 1)
		{
			system++;
			wait1Msec(400);
		}
		//-------------------------------------------------
		if(nNxtButtonPressed == 2)
		{
			system--;
			wait1Msec(400);
		}
		//-------------------------------------------------
		switch (system)
		{
		case 0: nxtDisplayCenteredTextLine(6, "Battery Power");break;
		case 1: nxtDisplayCenteredTextLine(6, "Drivetrain");break;
		case 2: nxtDisplayCenteredTextLine(6, "Gripper");break;
		case 3: nxtDisplayCenteredTextLine(6, "Arm");break;
		case 4: nxtDisplayCenteredTextLine(6, "BAM");break;
		case 5: nxtDisplayCenteredTextLine(6, "Mechanical Stop");break;
		case 6: nxtDisplayCenteredTextLine(6, "Gyro Sensor");break;
		case 7: nxtDisplayCenteredTextLine(6, "EOPD Sensor");break;
		case 8: nxtDisplayCenteredTextLine(6, "Color Sensor");break;
		}
		//---------------------------------------------------------------
		if(nNxtButtonPressed == 3)
		{
			eraseDisplay();
			break;
		}
		//---------------------------------------------------------------
	}
}
//////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();
	////////////////////////////////////////////////////////////////////////////
	while(true)
	{
		selectProgram();

		switch(system)
		{
		case 0:
			while(true)
			{
				//----------------------------
				if(nNxtButtonPressed == 1)
				{
					rechargable = false;
					wait1Msec(400);
				}
				//----------------------------
				if(nNxtButtonPressed == 2)
				{
					rechargable = true;
					wait1Msec(400);
				}
				//------------------------------------------------------
				switch (rechargable)
				{
				case false: nxtDisplayCenteredTextLine(6, "Batteries");
					bNxtRechargable = false;
					break;
				case true: nxtDisplayCenteredTextLine(6, "Rechargable");
					bNxtRechargable = true;
					break;
				}
				//------------------------------------------------------
				if(nNxtButtonPressed == 3)
				{
					eraseDisplay();
					break;
				}
			//--------------------------------------------------------
			}
			ClearTimer(T1);
			while(time1(T1) < 4000)
			{
				string in = nImmediateBatteryLevel;
				string ex = externalBattery;
				nxtDisplayCenteredTextLine(5, in);
				nxtDisplayCenteredTextLine(7, ex);
			}
			break;

			//Drivetrain Test//////////////////////////////////////////////////////////
		case 1:
			motor[LeftMotor] = 50;
			wait10Msec(200);
			motor[LeftMotor] = 0;
			//-----------------------
			motor[LeftMotor] = -50;
			wait10Msec(200);
			motor[LeftMotor] = 0;
			//-----------------------
			motor[RightMotor] = 50;
			wait10Msec(200);
			motor[RightMotor] = 0;
			//-----------------------
			motor[RightMotor] = -50;
			wait10Msec(200);
			motor[RightMotor] = 0;
			//-----------------------
			motor[LeftMotor] = 50;
			motor[RightMotor] = 50;
			wait10Msec(200);
			motor[LeftMotor] = 0;
			motor[RightMotor] = 0;
			//-----------------------
			motor[LeftMotor] = 50;
			motor[RightMotor] = 50;
			wait10Msec(200);
			motor[LeftMotor] = 0;
			motor[RightMotor] = 0;
			//-----------------------
			break;

			//Gripper Test//////////////////////////////////////////////////////////
		case 2:
			//nMotorEncoderTarget[finger] = 90;
			//ClearTimer(T1);
			//while ((nMotorEncoder[finger] < 90) && (time1[T1] < 500))
			//{
			//	motor[finger] = 30;
			//}
			//wait10Msec(100);
			////-------------------------------------------------------
			//nMotorEncoderTarget[finger] = 0;
			//ClearTimer(T1);
			//while ((nMotorEncoder[finger] > 0) && (time1[T1] < 500))
			//{
			//	motor[finger] = -30;
			//}
			//motor[finger] = 0;

			break;

			//Arm Test////////////////////////////////////////////////////////////////
		case 3:
			//-----------------------------
			motor[lifter] = 20;
			wait10Msec(300);
			//-----------------------------
			motor[lifter] = -20;
			wait10Msec(300);
			//-----------------------------
			break;
			//BAM/////////////////////////////////////////////////////////////////////
		case 4:
			servoTarget[BamContL] = 255;
			servoTarget[BamContR] = 0;
			wait10Msec(200);
			//------------------------------
			servoTarget[BamContL] = 0;
			servoTarget[BamContR] = 255;
			wait10Msec(200);
			//------------------------------
			servoTarget[BamContL] = 127;
			servoTarget[BamContR] = 127;
			wait10Msec(200);
			break;
			//Mechanical Stop/////////////////////////////////////////////////////////
		case 5:
			servoTarget[RamLeft] = 255;
			servoTarget[RamRight] = 0;
			wait10Msec(200);
			//------------------------------
			servoTarget[RamLeft] = 0;
			servoTarget[RamRight] = 255;
			wait10Msec(200);
			//------------------------------
			servoTarget[RamLeft] = 127;
			servoTarget[RamRight] = 127;
			wait10Msec(200);
			break;
			//Gyro/////////////////////////////////////////////////////////////////////
		case 6:
			turngyro(90, 30);
			wait10Msec(200);
			//----------------------------
			turngyro(-90, 30);
			wait10Msec(200);
			//----------------------------
			turngyro(45, 30);
			wait10Msec(200);
			//----------------------------
			turngyro(-45, 30);
			wait10Msec(200);
			break;
		}
	}
}
