#pragma config(Sensor, S1,     rgbSensor,      sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "LEGOLS-driver.h"

task main()
{
	while(true)
	{
		int sensorVal = SensorValue[rgbSensor];
		nxtDisplayTextLine(2, "RGB:%d", sensorVal);
		int sensorValR = sensorRaw[rgbSensor];
		//nxtDisplayTextLine(4, "RGB:%d", sensorValR);
	}
}
