#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     Light,          sensorLightInactive)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          finger,        tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    bamLeft,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bamRight,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*THIS CODE ALL WORKS AS IS 11-11 mary hwang */
#include "Measurments.V2.c"
#include "MoveCommandsV1[2012-2013].c"
#include "JoystickDriver.c"

task main()
{
 	initializeRobot();

 	int motorSpeed = 7;

 	ClearTimer(T1);
 	/*while (true)
 	{
 		int light = SensorValue[Light];
 	nxtDisplayBigTextLine(3, "%d", light); }*/
	motor[LeftMotor] = 10;
  motor[RightMotor] = 10;
	wait1Msec(500);

	while (Time1[T1] < 20000)
	{
    while(SensorValue[Light] < 15)
		{
			motor[LeftMotor] = -motorSpeed;
			motor[RightMotor] = motorSpeed;
		}

		while (SensorValue[Light] >= 15)
		{
		motor[LeftMotor] = motorSpeed;
		motor[RightMotor]= motorSpeed;
		}


		while(SensorValue[Light] < 15)
		{
			motor[LeftMotor] = motorSpeed;
			motor[RightMotor] = -motorSpeed;
		}
		while (SensorValue[Light] >= 15)
		{
		motor[LeftMotor] = motorSpeed;
		motor[RightMotor]= motorSpeed;
		}
 }
}
