#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          Gripper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     jointOne,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     jointTwo,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "MoveCommandsV1[2012-2013]"
int system = 0;

/////////////////////////////////////////////////////////////////////////////////////
void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	//the servos are initialzed here so that in the event that a crate is held in autonomous it will not be dropped

	motor[RightMotor] = 0;
	motor[LeftMotor] = 0;

	nMotorEncoder[finger] = 0;
	nMotorEncoder[arm] = 0;
	nMotorEncoder[LeftMotor] = 0;
	nMotorEncoder[RightMotor] = 0;
	servoTarget[bamLeft] = 0;
	servoTarget[bamRight] = 255;
	ClearTimer(T1);
	while(time1[T1] < 1000)
	{
		motor[finger] = -30;
	}
	nMotorEncoder[finger] = 0;
	motor[finger] = 0;
	servoTarget[stopLeft] = 0;
	servoTarget[stopRight] = 255;
	return;
}

//////////////////////////////////////////////////////////////////////////
void selectProgram()
{
	eraseDisplay();
	// Enable Top Line NXT Display (Bluetooth, NXT Name & Battery Status)
	bNxtLCDStatusDisplay = true;
	// StopAllTasks();
	while(true)
	{
		nxtDisplayCenteredTextLine(1,"DITU SAYS WEAR");
		nxtDisplayCenteredTextLine(2,"SAFETY GLASSES");
		nxtDisplayCenteredTextLine(4, "Select Test:");

		if(nNxtButtonPressed == 1)
		{
			system++;
			wait1Msec(400);
		}
		if(nNxtButtonPressed == 2)
		{
			system--;
			wait1Msec(400);
		}
		switch (system)
		{
		case 0: nxtDisplayCenteredTextLine(6, "Battery Power");break;
		case 1: nxtDisplayCenteredTextLine(6, "Drivetrain");break;
		case 2: nxtDisplayCenteredTextLine(6, "Gripper");break;
		case 3: nxtDisplayCenteredTextLine(6, "Arm");break;
		case 4: nxtDisplayCenteredTextLine(6, "BAM");break;
		case 5: nxtDisplayCenteredTextLine(6, "Mechanical Stop");break;
		case 6: nxtDisplayCenteredTextLine(6, "Gyro Sensor");break;
		case 7: nxtDisplayCenteredTextLine(6, "EOPD Sensor");break;
		case 8: nxtDisplayCenteredTextLine(6, "Color Sensor");break;
		case 9: nxtDisplayCenteredTextLine(6, "Drawbridge Latch");break;
		case 10: nxtDisplayCenteredTextLine(6, "MagBall Stopper"); break;
		case 11: nxtDisplayCenteredTextLine(6, "Finger Servos"); break;
		case 12: nxtDisplayCenteredTextLine(6, "S-Mux Battery"); break;
		case 13: nxtDisplayCenteredTextLine(6, "Proto Board"); break;
		case 14: nxtDisplayCenteredTextLine(6, "Magnet Ball Test");break;
		case 15: nxtDisplayCenteredTextLine(6, "Gyro Test");break;
		}
		if(nNxtButtonPressed == 3)
		{
			eraseDisplay();
			break;
		}
	}
}
//////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();
	////////////////////////////////////////////////////////////////////////////
	while(true)
	{

		selectProgram();

		switch(system)
		{
		case 0:

			break;

		//Drivetrain Test//////////////////////////////////////////////////////////
		case 1:
			motor[leftDrive] = 50;
			wait10Msec(200);
			motor[leftDrive] = 0;
			//-----------------------
			motor[leftDrive] = -50;
			wait10Msec(200);
			motor[leftDrive] = 0;
			//-----------------------
			motor[rightDrive] = 50;
			wait10Msec(200);
			motor[rightDrive] = 0;
			//-----------------------
			motor[rightDrive] = -50;
			wait10Msec(200);
			motor[rightDrive] = 0;
			//-----------------------
			motor[leftDrive] = 50;
			motor[rightDrive] = 50;
			wait10Msec(200);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			//-----------------------
			motor[leftDrive] = 50;
			motor[rightDrive] = 50;
			wait10Msec(200);
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			//-----------------------
			break;

		//Gripper Test//////////////////////////////////////////////////////////
		case 2:
			nMotorEncoderTarget[finger] = 90;
			ClearTimer(T1);
			while ((nMotorEncoder[finger] < 90) && (time1[T1] < 500))
			{
				motor[finger] = 30;
			}
			wait10Msec(100);
			//-------------------------------------------------------
			nMotorEncoderTarget[finger] = 0;
			ClearTimer(T1);
			while ((nMotorEncoder[finger] > 0) && (time1[T1] < 500))
			{
				motor[finger] = -30;
			}
			motor[finger] = 0;

			break;

		//Arm Test////////////////////////////////////////////////////////////////
		case 3:
			//-----------------------------
			motor[arm] = 20;
			wait10Msec(300);
			//-----------------------------
			motor[arm] = -20;
			wait10Msec(300);
			//-----------------------------
			break;
		//BAM/////////////////////////////////////////////////////////////////////
		case 4:
			servoTarget[bamLeft] = 255;
			servoTarget[bamRight] = 0;
			wait10Msec(200);
			//------------------------------
			servoTarget[bamLeft] = 0;
			servoTarget[bamRight] = 255;
			wait10Msec(200);
			//------------------------------
			servoTarget[bamLeft] = 127;
			servoTarget[bamRight] = 127;
			wait10Msec(200);
			break;
		//Mechanical Stop/////////////////////////////////////////////////////////
		case 5:
			servoTarget[stopLeft] = 255;
			servoTarget[stopRight] = 0;
			wait10Msec(200);
			//------------------------------
			servoTarget[stopLeft] = 0;
			servoTarget[stopRight] = 255;
			wait10Msec(200);
			//------------------------------
			servoTarget[stopLeft] = 127;
			servoTarget[stopRight] = 127;
			wait10Msec(200);
			break;
		//Gyro/////////////////////////////////////////////////////////////////////
		case 6:
			turngyro_right(90, 30);
			wait10Msec(200);
			//----------------------------
			turngyro_right(-90, 30);
			wait10Msec(200);
			//----------------------------
			turngyro_right(45, 30);
			wait10Msec(200);
			//----------------------------
			turngyro_right(-45, 30);
			wait10Msec(200);
			break;
		}
	}
}
