#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          Gripper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightDrive] = 100;
motor[leftDrive] = 100;
wait1Msec(5000);
motor[rightDrive] = -100;
motor[leftDrive] = -100;
wait1Msec(5000);
//servoTarget[BAM] = 255;
//wait1Msec(2000);
//servoTarget[BAM] = 64;
//wait1Msec(2000);
//motor[jointOne] = 100;
//motor[jointOne] = -100;
//wait1Msec(2000);
//motor[jointTwo] = 100;
//motor[jointTwo] = -100;
//wait1Msec(2000);
//motor[Gripper] = 50;
//wait1Msec(2000);
//motor[Gripper] = -50;
//wait1Msec(2000);
//int IR_Value = sensorValue[IR];
}
