#pragma config(Hubs,	S1, HTMotor,	HTMotor,	HTMotor,	HTServo)
#pragma config(Sensor, S1,		 ,							 sensorI2CMuxController)
#pragma config(Motor,	 motorA,					gripper,			 tmotorNXT, PIDControl, encoder)
#pragma config(Motor,	 mtr_S1_C1_1,			rightDrive,		 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C1_2,			leftDrive,		 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C2_1,			armMotor,			 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C2_2,			motorG,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C3_1,			motorH,				 tmotorTetrix, openLoop)
#pragma config(Motor,	 mtr_S1_C3_2,			motorI,				 tmotorTetrix, openLoop)
#pragma config(Servo,	 srvo_S1_C4_1,		BAMleft,							tServoStandard)
#pragma config(Servo,	 srvo_S1_C4_2,		BAMright,							tServoStandard)
#pragma config(Servo,	 srvo_S1_C4_3,		servo3,								tServoNone)
#pragma config(Servo,	 srvo_S1_C4_4,		servo4,								tServoNone)
#pragma config(Servo,	 srvo_S1_C4_5,		servo5,								tServoNone)
#pragma config(Servo,	 srvo_S1_C4_6,		servo6,								tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//
#include "JoystickDriver.c"

task main()
{
	while (true)
	{
		getJoystickSettings(joystick);
		// test right side drive train
		if (joy1Btn(4))
		{
			motor[rightDrive] = 100;
			wait1Msec(3000);
			motor[rightDrive] = 0;
		}
		// test left side drive train
		if (joy1Btn(1))
		{
			motor[leftDrive] = 100;
			wait1Msec(3000);
			motor[leftDrive] = 0;
		}
		// test BAM
		if (joy1Btn(3))
		{
			servoTarget[BAMright] = 255;
			servoTarget[BAMleft] = 0;
			wait1Msec(3000);
		}
		// test arm
		if (joy1Btn(2))
		{
			motor[armMotor] = 100;
			motor[armMotor] = 0;
			wait1Msec(3000);
		}
	}
}
