#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Light,          sensorLightInactive)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          finger,        tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    bamLeft,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bamRight,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////
/// File Name: Teleop.V2.c
/// Creator: Chris Beck, Joslyn, Sou
/// Date of Creation: [11/16/12]
/// Last Editor: Chris Beck
///
/// Changes: Modifications to logic to enable correct functioning of code and corrections of errors.
///
/// Description:5
///		The teleoperated main program
///
///////////////////////////////////////////////

#include "JoystickDriver.c"

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  //the servos are initialzed here so that in the event that a crate is held in autonomous it will not be dropped

  motor[RightMotor] = 0;
  motor[LeftMotor] = 0;

  nMotorEncoder[finger] = 0;
 	nMotorEncoder[arm] = 0;
  nMotorEncoder[LeftMotor] = 0;
  nMotorEncoder[RightMotor] = 0;
  servoTarget[bamLeft] = 0;
  servoTarget[bamRight] = 255;
  ClearTimer(T1);
	while(time1[T1] < 1000)
  	{
    	motor[finger] = -30;
    }
  nMotorEncoder[finger] = 0;
  motor[finger] = 0;
  return;
}
bool speed = true;
////////////////////////////////////////////////////////////////////////////////////////
task main()
{
	waitForStart();
	initializeRobot();

	while(true)
	{
		getJoystickSettings(joystick);
		int jLeft = (int)joystick.joy1_y1;
		int jRight = -(int)joystick.joy1_y2;

////Drivetrain/////////////////////////////////////////////////////////////////////////

		if(joy1Btn(5))
		{
			speed = true;
		}
		if(joy1Btn(7))
		{
			speed = false;
		}

		if (speed)
		{
			if (abs(jLeft) < 10)            ///< core out the noise for near zero settings
      	motor[LeftMotor] = 0;         ///< sets the left motor to 0% power
    	else
      	motor[LeftMotor] = jLeft;     ///< set motors to joystick settings
    	if (abs(jRight) < 10)           ///< core out the noise for near zero settings
      	motor[RightMotor] = 0;        ///< sets the right motor to 0% power
    	else
      	motor[RightMotor] = jRight;   ///< sets motors to joystick settings
		}

		else
		{
    	if (abs(jLeft) < 10)            ///< core out the noise for near zero settings
      	motor[LeftMotor] = 0;         ///< sets the left motor to 0% power
    	else
      	motor[LeftMotor] = (jLeft/5);   ///< set motors to joystick settings
    	if (abs(jRight) < 10)           ///< core out the noise for near zero settings
      	motor[RightMotor] = 0;        ///< sets the right motor to 0% power
    	else
      	motor[RightMotor] = (jRight/5); ///< sets motors to joystick settings
		}
		/*
		if(speed == false){
			if (abs(jLeft) < 10)            ///< core out the noise for near zero settings
      	motor[LeftMotor] = 0;         ///< sets the left motor to 0% power
    	else
      	motor[LeftMotor] = jLeft;     ///< set motors to joystick settings
    	if (abs(jRight) < 10)           ///< core out the noise for near zero settings
      	motor[RightMotor] = 0;        ///< sets the right motor to 0% power
    	else
      	motor[RightMotor] = jRight;   ///< sets motors to joystick settings
    }
    if(speed){
    	if (abs(jLeft) < 10)            ///< core out the noise for near zero settings
      	motor[LeftMotor] = 0;         ///< sets the left motor to 0% power
    	else
      	motor[LeftMotor] = (jLeft/2);   ///< set motors to joystick settings
    	if (abs(jRight) < 10)           ///< core out the noise for near zero settings
      	motor[RightMotor] = 0;        ///< sets the right motor to 0% power
    	else
      	motor[RightMotor] = (jRight/2); ///< sets motors to joystick settings
			}*/

//////Arm//////////////////////////////////////////////////////////////////////////////
      //up
      if(joy2Btn(5))
      {
				motor[arm] = 20;
      }
      //down
      else if(joy2Btn(7))
      {
				motor[arm] = -20;
      }
  		else
  		{
  			motor[arm] = 0;
  		}

//////BAM////////////////////////////////////////////////////////////////////////////////
      //up
      if(joy1Btn(8))
      {
      	servoTarget[bamLeft] = 255;
      	servoTarget[bamRight] = 0;
    	}
    	//down
    	else if(joy1Btn(6))
      {
      	servoTarget[bamLeft] = 0;
      	servoTarget[bamRight] = 255;
    	}
			else
			{
      	servoTarget[bamLeft] = 127;
      	servoTarget[bamRight] = 127;
    	}

//////Fingers///////////////////////////////////////////////////////////////////////////////
    	if(joy2Btn(6))
    	{
    		nMotorEncoderTarget[finger] = 90;
    		ClearTimer(T1);
    		while ((nMotorEncoder[finger] < 90) && (time1[T1] < 500))
    		{
    			motor[finger] = 30;
   			}
    	}

    	if(joy2Btn(8))
    	{
    		nMotorEncoderTarget[finger] = 0;
    		ClearTimer(T1);
    		while ((nMotorEncoder[finger] > 0) && (time1[T1] < 500))
    		{
    			motor[finger] = -30;
   			}
   			motor[finger] = 0;
    	}
    }
	}
////////////////////////////////////////////////////////////////////////////////////////////


//End of File//
