#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     Touch,          sensorTouch)
#pragma config(Motor,  motorA,          stopLeft,      tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,          stopRight,     tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     RightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lifter,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    ramp,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    bamLeft,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    bamRight,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////
/// File Name: Teleop.V4.c
/// Creator: Chris Beck, Joslyn, Sou
/// Date of Creation: [12/10/12]
/// Last Editor: Chris Beck
///
/// Changes: Modifications to logic to enable correct functioning of code and corrections of errors.
///
/// Description:
///		The teleoperated main program
///
///////////////////////////////////////////////
#include "JoystickDriver.c"

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	//the servos are initialzed here so that in the event that a crate is held in autonomous it will not be dropped

	motor[RightMotor] = 0;
	motor[LeftMotor] = 0;

	nMotorEncoder[lifter] = 0;
	nMotorEncoder[LeftMotor] = 0;
	nMotorEncoder[RightMotor] = 0;
	servoTarget[bamLeft] = 0;
	servoTarget[bamRight] = 254;
	motor[stopLeft] = 50;
	motor[stopRight] = 50;
	wait10Msec(100);
	motor[stopLeft] = 0;
	motor[stopRight] = 0;
	nMotorEncoder[stopLeft] = 0;
	nMotorEncoder[stopRight] = 0;
	return;
}
bool speed = true;
////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	waitForStart();
	initializeRobot();

	while(true)
	{
		getJoystickSettings(joystick);
		int jLeft = (int)joystick.joy1_y1;
		int jRight = -(int)joystick.joy1_y2;


		//Driver Controls//////////////////////////////////////////////////////////////////////////

		//////Drivetrain///////////////////////////////////////////////////////////////////////
		//Speed Control//
		if(joy1Btn(5))
		{
			speed = true;
		}
		//------------------------------
		if(joy1Btn(7))
		{
			speed = false;
		}
		//-------------------------------
		if (speed)
		{
			if (abs(jLeft) < 10)            ///< core out the noise for near zero settings
				motor[LeftMotor] = 0;         ///< sets the left motor to 0% power
			else
				motor[LeftMotor] = jLeft;     ///< set motors to joystick settings
			if (abs(jRight) < 10)           ///< core out the noise for near zero settings
				motor[RightMotor] = 0;        ///< sets the right motor to 0% power
			else
				motor[RightMotor] = jRight;   ///< sets motors to joystick settings
		}
		//--------------------------------
		else
		{
			if (abs(jLeft) < 10)              ///< core out the noise for near zero settings
				motor[LeftMotor] = 0;           ///< sets the left motor to 0% power
			else
				motor[LeftMotor] = (jLeft/3);   ///< set motors to joystick settings
			if (abs(jRight) < 10)             ///< core out the noise for near zero settings
				motor[RightMotor] = 0;          ///< sets the right motor to 0% power
			else
				motor[RightMotor] = (jRight/3); ///< sets motors to joystick settings
		}

		//CURRENTLY NULL//
		/*

		//////BAM////////////////////////////////////////////////////////////////////////////////
		//up
		if(joy1Btn(8))
		{
			servoTarget[bamLeft] = 255;
			servoTarget[bamRight] = 0;
		}
		//down
		else if(joy1Btn(6))
		{
			servoTarget[bamLeft] = 0;
			servoTarget[bamRight] = 255;
		}
		//Idle
		else
		{
			servoTarget[bamLeft] = 127;
			servoTarget[bamRight] = 127;
		}

		*/

		//Manipulator Controls/////////////////////////////////////////////////////////////////////

		//////lifter///////////////////////////////////////////////////////////////////////////////

		int touchVal;
		touchVal = SensorValue(Touch);

		int lifterEncoderVal;
		lifterEncoderVal = nMotorEncoder[lifter];

		nxtDisplayCenteredBigTextLine(2, "%d", touchVal);
		nxtDisplayCenteredBigTextLine(5, "%d", lifterEncoderVal);

		//up
		if(joy2Btn(7) && (touchVal == 0))
		{
			motor[lifter] = -50;
		}
		//down
		else if(joy2Btn(5))
		{
			motor[lifter] = 50;
		}
		//Idle
		else
		{
			motor[lifter] = 0;
		}


		//OVERRIDE
		//down
		if(joy2Btn(4))
		{
			motor[lifter] = 50;
		}

		/*
		float encoderVal;
		nMotorEncoder[lifter] = encoderVal;
		nxtDisplayBigTextLine(2, "encoder val: %lf", encoderVal);
		*/
		/*

		//////Mechanical Stop/////////////////////////////////////////////////////////////////////////
		//Down////
		if(joy2Btn(2))
		{
			nMotorEncoderTarget[stopLeft] = 90;
			nMotorEncoderTarget[stopRight] = 90;
			ClearTimer(T1);
			while ((nMotorEncoder[stopLeft] < 90) && (time1[T1] < 500))
			{
				motor[stopLeft] = -30;
				motor[stopRight] = -30;
			}
		}

		//Up////
		if(joy2Btn(4))
		{
			nMotorEncoderTarget[stopLeft] = 0;
			nMotorEncoderTarget[stopRight] = 0;
			ClearTimer(T1);
			while ((nMotorEncoder[stopLeft] > 0) && (time1[T1] < 500))
			{
				motor[stopLeft] = 30;
				motor[stopRight] = 30;
			}
			motor[stopLeft] = 0;
			motor[stopRight] = 0;
		}

		*/

		//Ramp/////////////////////////////////////////////////////////////////////////
		if(joy2Btn(10))
		{
			ClearTimer(T1);
			while(time1[T1] < 1000)
			{
				servoTarget[ramp] = 255;
			}
		}
	}
}
////////////////////////////////////////////////////////////////////////////////////////////


//End of File//
