#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTPB,           sensorI2CCustom9V)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          Wheel,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          LeftDrawbridge, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          RightDrawbridge, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rArm,          tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lArm,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Intake,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Roller,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    conveyorservo,        tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    rightServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    leftServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    magnetballStopper,    tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
//#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
//#pragma config(Motor,  motorA,          BAsys,         tmotorNXT, PIDControl, encoder)
//#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
//#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////
/// File Name: Teleop.V1.c
/// Creator: Chris Beck
/// Date of Creation: [10/17/12]
/// Last Editor: N/A
///
/// Changes: N/A
///
/// Description:
///		The teleoperated main program
///
///////////////////////////////////////////////

#inlcude "JoystickDriver.c"
task main()
{
jLeft = (int)joystick.joy1_y1;
jRight = (int)joystick.joy1_y2;

if (abs(jLeft) < 10)          		///< core out the noise for near zero settings
      motor[LeftMotor] = 0;       ///< sets the left motor to 0% power
    else
      motor[LeftMotor] = jLeft;   ///< set motors to joystick settings

    if (abs(jRight) < 10)         ///< core out the noise for near zero settings
      motor[RightMotor] = 0;      ///< sets the right motor to 0% power
    else
      motor[RightMotor] = jRight; ///< sets motors to joystick settings
}
