#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     LeftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
//#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
//#pragma config(Motor,  motorA,          BAsys,         tmotorNXT, PIDControl, encoder)
//#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
//#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
//#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////
/// File Name: Teleop.V1.c
/// Creator: Chris Beck, Joslyn, Sou
/// Date of Creation: [10/17/12], [10/19/12]
/// Last Editor: Chris Beck
///
/// Changes: Modifications to logic to enable correct functioning of code and corrections of errors.
///
/// Description:
///		The teleoperated main program
///
///////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  //the servos are initialzed here so that in the event that a crate is held in autonomous it will not be dropped

  motor[RightMotor] = 0;
  motor[LeftMotor] = 0;

  return;
}

task main()
{
	initializeRobot();
	waitForStart();

	while(true)
	{
		int jLeft = (int)joystick.joy1_y1;
		int jRight = (int)joystick.joy1_y2;

		if (abs(jLeft) < 10)          ///< core out the noise for near zero settings
      motor[LeftMotor] = 0;       ///< sets the left motor to 0% power
    else
      motor[LeftMotor] = jLeft;   ///< set motors to joystick settings

    if (abs(jRight) < 10)         ///< core out the noise for near zero settings
      motor[RightMotor] = 0;      ///< sets the right motor to 0% power
    else
      motor[RightMotor] = jRight; ///< sets motors to joystick settings

      /*
      if(jLeft > 0)
      	motor[LeftMotor] = jLeft;
     	if(jRight > 0)
     		motor[RightMotor] = jRight;
    */
     		}
}
