#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontElevator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool resetEncodersAtBeginning(bool resetEncoders)
{
	//resets encoders at the beginning
	if(resetEncoders)
	{
		motor[frontElevator] = -10;
		if(SensorValue[TouchTop] == 1) //may be wrong sensorvalue output
		{
			motor[frontElevator] = 0;
			nMotorEncoder[frontElevator] = 0;
			resetEncoders = false;
		}
	}
}

int readJoystick(int value)
{
	if (joy2Btn()) // 1 height
		value = (int)1440*18/(2*PI);
	else if (joy2Btn()) // 2 height
		value = (int)1440*32/(2*PI);
	else if (joy2Btn()) // 3 height
		value = (int)1440*46/(2*PI);
	return value;
}

//checks to see if you want to score rings in one or two stage
bool isAuto(bool value)
{
	if (joy2Btn())
		value = true;
	else
		value = false;
	return value;
}

int elevatorGoToHeight(int Xdesired)
{
	int Xcurrent;
	int errorX;
	int Xspeed;
	//int lifterEncoderVal;
	int touchValTop = 0;
	int touchValBottom = 0;
	bool automode;
	int elevatorDirection = 1;
	int proportionConstant = 1; // figure this out!!!!
	automode = true;
	Xcurrent = nMotorEncoder[frontElevator];

	while(Xcurrent != Xdesired && touchValBottom == 0 && touchValTop == 0)
	{
		Xdesired = readJoystick(Xdesired);  //reads controller to see if fickle user wants to go somewhere else instead

		//reads the touch values
		touchValBottom = SensorValue[TouchBottom];
		touchValTop = SensorValue[TouchTop];

		//reads xcurrent
		Xcurrent = nMotorEncoder[frontElevator];

		//calculates what the distance you still need to go and determines the adjusted speed
		errorX = Xdesired - Xcurrent;

		//back up if overshoot
		if (Xcurrent > Xdesired)
			elevatorDirection = elevatorDirection * -1;

		//////////////////////////////////////////////////////////
		//////////           SETS THE SPEED             //////////
		//////////////////////////////////////////////////////////
		Xspeed = proportionConstant * errorX * elevatorDirection;
		//////////////////////////////////////////////////////////

		//corrects speed for distances over 100
		if(abs(Xspeed) > 100)
			Xspeed = 100*elevatorDirection;

		//sets the speed of the motors
		motor[backElevator] = Xspeed*-1;
		motor[frontElevator] = Xspeed;

		//stop button
		if(joy2Btn() == 1)
		{
			motor[backElevator] = 0;
			motor[frontElevator] = 0;
			break;
		}
	}

	motor[backElevator] = 0;
	motor[frontElevator] = 0;
	return 0;
}

void dispenseRings()
{
	int value = 130;
	servoTarget[gripper] = value;
	return;
}

task Lifter()
{
	int Xdesired; // the encoder value of height we want to obtain
	int Xcurrent;
	//int lifterEncoderVal;
	int touchValTop;
	int touchValBottom;
	bool automode;
	int elevatorDirection = 1;
	int home = (int)1440*18/(2*PI);
	int pickUpRings = -5;
	int value;
	bool resetEncoders = true;

	automode = true;
	//int joystickCurrent;

	while (true)
	{
		///////////////////////////////////////////////////
		/////    INITIALIZATION & NON-MOVING STUFF    /////
		///////////////////////////////////////////////////

		//reads the touch sensors
		touchValBottom = SensorValue[TouchBottom];
		touchValTop = SensorValue[TouchTop];

		resetEncodersAtBeginning(resetEncoders);

		//sets the value of xcurrent and xdesired
		Xcurrent = nMotorEncoder[frontElevator];
		Xdesired = readJoystick(Xcurrent);

		bool mode = isAuto(value);

		///////////////////////////////////////////////////
		/////       ACTUAL TELE-OP MOVING STUFF       /////
		///////////////////////////////////////////////////

		if (Xdesired != Xcurrent)
		{
			elevatorGoToHeight(pickUpRings);
			elevatorGoToHeight(Xdesired);
			//if 1 stage
			if (mode)
			{
				dispenseRings();
				elevatorGoToHeight(home);
				mode = 0;
			}
		}

		if(joy1Btn(5))
			motor[frontMotor] = 100;
		if(joy1Btn(7))
			motor[frontMotor] = -100;
		else
			motor[frontMotor] = 0;


		//dispense rings
		if (joy2Btn() == 1)
			dispenseRings();

		//stop button
		if(joy2Btn() == 1)
		{
			motor[backElevator] = 0;
			motor[frontElevator] = 0;
			break;
		}
	}
}
