#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontElevator, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Sensor, S1,     HTPB,           sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "C:\Users\ditu\Documents\GitHub\RingItUp2012-2013\Utilities\Robotc Includes\hitechnic-protoboard.h"

int readJoystick(int value)
{
	if (joy2Btn(2)) // 1 height
		value = (int)1440*18/(2*PI);
/*
	else if (joy2Btn(3)) // 2 height
		value = (int)1440*32/(2*PI);
	else if (joy2Btn(4)) // 3 height
		value = (int)1440*46/(2*PI);*/
	return value;
}

int elevatorGoToHeight(int Xdesired)
{
	int Xcurrent;
	int errorX;
	int Xspeed;
	//int lifterEncoderVal;
	bool automode;
	int elevatorDirection = 1;
	int proportionConstant = 1; // figure this out!!!!
	automode = true;
	Xcurrent = nMotorEncoder[frontElevator];

	while(Xcurrent != Xdesired)//& touchValBottom == 0 && touchValTop == 0)
	{
		Xdesired = readJoystick(Xdesired);  //reads controller to see if fickle user wants to go somewhere else instead

		//reads the touch values
		//touchValBottom = SensorValue[TouchBottom];
		//touchValTop = SensorValue[TouchTop];

		//reads xcurrent
		Xcurrent = nMotorEncoder[frontElevator];

		//calculates what the distance you still need to go and determines the adjusted speed
		errorX = Xdesired - Xcurrent;

		//back up if overshoot
		if (Xcurrent > Xdesired)
			elevatorDirection = elevatorDirection * -1;

		//////////////////////////////////////////////////////////
		//////////           SETS THE SPEED             //////////
		//////////////////////////////////////////////////////////
		Xspeed = proportionConstant * errorX * elevatorDirection;
		//////////////////////////////////////////////////////////

		//corrects speed for distances over 100
		if(abs(Xspeed) > 100)
			Xspeed = 100*elevatorDirection;

		//sets the speed of the motors
		motor[frontElevator] = Xspeed;

		//stop button
		if(joy2Btn(6) == 1)
		{
			motor[frontElevator] = 0;
			break;
		}
		nxtDisplayString(3, "ErrorX %d", errorX);
		nxtDisplayString(5, "K =    %lf", proportionConstant);
	}

	motor[frontElevator] = 0;
	return 0;
}



task main()
{
	int Xdesired = 0;
	getJoystickSettings(joystick);

	nMotorEncoder[frontElevator] = 0;

	while(true)
	{
		Xdesired = readJoystick(Xdesired);
		//manual overrides
		elevatorGoToHeight(Xdesired);
		motor[frontElevator] = 0;

	}
}
